version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2.7
      - image: circleci/mysql:8
    environment:
      CP_MYSQL_TEST_HOST: "127.0.0.1"
      CP_MYSQL_TEST_PASSWORD: ""
      CP_MYSQL_TEST_USER: "root"
    steps:
      - checkout
      - run: sudo apt-get install default-jdk
      - run: sudo -H pip install --progress-bar off cython numpy
      - run: sudo -H pip install --progress-bar off .[test]
      - run: py.test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
